name: loyihani testlash
on:
  push:
    branches: [main,dev]

jobs:
  clone:
      runs-on: windows-latest
      steps:
        - name: githabga loyihani yuklash 
          uses: actions/checkout@v4

        - name: Lunixmi
          run: uname -s

        - name: node_modules'in ornatish
          run: npm i
        
        - name: Build qilish
          run: npm run build

