name: CI
on:
  push:
    branches: [main]

jobs:
  Repositoriyani_yuklash:
      runs-on: ubuntu-latest
      steps:
         - name: Repositoriyni githabga yuklash
           uses: actions/checkout

         - name: node js ornatish
           uses: actions/setup-node
