# name: loyihani testlash
# on:
#   push:
#     branches: [main,dev]

# jobs:
#   clone:
#       runs-on: ubuntu-latest
#       steps:
#         - name: githabga loyihani yuklash 
#           uses: actions/checkout@v4

#         - name: nodejsni ornatish
#           uses: actions/setup-node@v5

#         - name: nodejs versiyasini tekshirish
#           run: node -v

#         - name: Lunixmi
#           run: uname -s

#         - name: node_modules'in ornatish
#           run: npm i
        
#         - name: Build qilish
#           run: npm run build


name: Loyihani testlash

on:
  push:
    branches: [main, dev]

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: GitHubga loyihani yuklash
        uses: actions/checkout@v4

  node_install:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Node.jsni o'rnatish
        uses: actions/setup-node@v5
        with:
          node-version: 22.17.0

  install_node_modules:
    needs: node_install
    runs-on: ubuntu-latest
    steps:
      - name: Repositoriyani yuklash
        uses: actions/checkout@v4
        
      - name: Package.json
        run: |
          ls

      - name: node_modules'ni o'rnatish
        run: npm i

  build:
    needs: install_node_modules
    runs-on: ubuntu-latest
    steps:
      - name: Repositoriyani yuklash
        uses: actions/checkout@v4

      - name: node_modules ornatish
        run: npm i

      - name: Build qilish
        run: npm run build