name: CI
on:
  push:
    branches: [main]

jobs:
  Repositoriyani_yuklash:
      runs-on: ubuntu-latest
      steps:
         - name: Repositoriyni githabga yuklash
           uses: actions/checkout@v3

         - name: node js ornatish
           uses: actions/setup-node@v3
           with:
            node-version: 18

